'use strict';
(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const products=JSON.parse(document.getElementById('product-data').textContent);
const wa=message=>'https://wa.me/5535998290565?text='+encodeURIComponent(message);
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(a.dataset.wa);a.target='_blank';a.rel='noopener noreferrer'});
const menu=document.querySelector('.menu-toggle'),nav=document.getElementById('mobile-nav');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');nav.hidden=true}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');nav.hidden=!open});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!nav.hidden){closeMenu();menu.focus()}});
const cards=[...document.querySelectorAll('.product')],query=document.getElementById('catalog-query');let selectedBrand='Todas',selectedType='',currentModel=0;
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function applyFilter(){let count=0;const q=norm(query.value.trim());cards.forEach(card=>{const p=products.find(p=>p.id===card.dataset.id);const text=norm([p.brand,p.name,p.detail,...p.features.map(f=>f.title+' '+f.text)].join(' '));card.hidden=(selectedBrand!=='Todas'&&p.brand!==selectedBrand)||(selectedType&&p.type!==selectedType)||(q&&!text.includes(q));if(!card.hidden)count++});document.querySelectorAll('[data-brand]').forEach(b=>{if(b.tagName!=='BUTTON')return;const active=b.dataset.brand===selectedBrand;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.getElementById('catalog-count').textContent=count+' '+(count===1?'referência':'referências')+' para explorar'+(selectedType?' · '+selectedType:'');document.getElementById('empty-state').hidden=count>0;document.getElementById('clear-filters').hidden=selectedBrand==='Todas'&&!selectedType&&!query.value;document.dispatchEvent(new Event('paraiso:filter'))}
function updateFilter(){if(document.startViewTransition&&!reduced.matches){const t=document.startViewTransition(applyFilter);t.ready.catch(()=>{});t.finished.catch(()=>{})}else applyFilter()}
document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{selectedBrand=b.dataset.brand;selectedType='';updateFilter()}));
let queryTimer;query.addEventListener('input',()=>{clearTimeout(queryTimer);queryTimer=setTimeout(updateFilter,120)});
function reset(){selectedBrand='Todas';selectedType='';query.value='';document.getElementById('site-query').value='';updateFilter()}
document.getElementById('clear-filters').addEventListener('click',reset);document.getElementById('reset-search').addEventListener('click',reset);
document.querySelector('.site-search').addEventListener('submit',e=>{e.preventDefault();selectedBrand='Todas';selectedType='';query.value=document.getElementById('site-query').value;applyFilter();document.getElementById('colecao').scrollIntoView({behavior:reduced.matches?'instant':'smooth'});query.focus({preventScroll:true})});
document.querySelectorAll('[data-select-brand]').forEach(a=>a.addEventListener('click',()=>{selectedBrand=a.dataset.selectBrand;selectedType='';query.value='';applyFilter()}));
document.querySelectorAll('[data-select-type]').forEach(a=>a.addEventListener('click',()=>{selectedBrand='Todas';selectedType=a.dataset.selectType;query.value='';applyFilter()}));
const image=document.getElementById('featured-image'),hotspots=[...document.querySelectorAll('.hotspot')];
const positions=[[[58,50],[48,39],[73,53]],[[57,54],[76,60],[43,47]],[[58,58],[40,51],[73,64]]];
function feature(index,animate=true){const p=products[currentModel],f=p.features[index];hotspots.forEach((b,i)=>{b.setAttribute('aria-expanded',String(i===index));b.setAttribute('aria-label','Conhecer '+p.features[i].title)});const panel=document.getElementById('feature-description');panel.querySelector('h4').textContent=f.title;panel.querySelector('p').textContent=f.text;if(animate){const note=document.getElementById('feature-note');note.hidden=false;note.querySelector('strong').textContent=f.title;note.querySelector('p').textContent=f.text;document.dispatchEvent(new CustomEvent('paraiso:feature',{detail:{index}}))}}
function model(index){document.getElementById('feature-note').hidden=true;currentModel=index;const p=products[index];image.src=p.image;image.alt=p.brand+' '+p.name+' em quarto ambientado com cama completa';document.getElementById('featured-name').textContent=p.name;document.getElementById('featured-detail').textContent=p.detail;document.getElementById('featured-consult').href=wa('Olá! Quero conhecer o '+p.brand+' '+p.name+'. Podem me informar medidas, valor, itens incluídos e disponibilidade?');document.getElementById('featured-source').href=p.source_url;document.querySelectorAll('[data-model]').forEach(b=>{const active=Number(b.dataset.model)===index;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});hotspots.forEach((b,i)=>{b.style.setProperty('--x',positions[index][i][0]+'%');b.style.setProperty('--y',positions[index][i][1]+'%')});const facts=document.getElementById('feature-facts');facts.replaceChildren(...p.features.map(f=>{const d=document.createElement('div'),h=document.createElement('h4'),t=document.createElement('p');h.textContent=f.title;t.textContent=f.text;d.append(h,t);return d}));feature(0,false);document.dispatchEvent(new CustomEvent('paraiso:model',{detail:{index}}))}
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('feature-note').hidden=true});hotspots.forEach((b,i)=>b.addEventListener('click',()=>feature(i)));document.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>model(Number(b.dataset.model))));document.querySelectorAll('[data-select-model]').forEach(a=>a.addEventListener('click',()=>model(Number(a.dataset.selectModel))));model(0);
const form=document.getElementById('comfort-form');
function summary(){const d=new FormData(form),size=d.get('size'),feel=d.get('feel'),brand=d.get('brand');document.querySelector('.guide-summary').textContent=[size,feel,brand].filter(v=>v&&v!=='Quero conhecer as opções').join(' · ')||'Seu tamanho. Seu toque. Seu próximo descanso.';document.getElementById('size-caption').textContent=size?(size==='Ainda preciso medir'?'Meça o quarto e a base antes de escolher':'Seu espaço para um colchão '+size.toLowerCase()):'Comece pelo espaço do seu quarto';const widths={Solteiro:48,Casal:75,Queen:90,King:110};document.querySelector('.bed-footprint').style.transform='rotate(-8deg) scaleX('+((widths[size]||70)/80)+')';document.querySelectorAll('.guide-progress i').forEach((i,n)=>i.classList.toggle('done',n===0?!!size:n===1?!!feel:brand!=='Quero conhecer as opções'));document.dispatchEvent(new Event('paraiso:guide'))}
form.addEventListener('change',summary);form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=new FormData(form);window.open(wa('Olá! Vim pelo guia da Paraíso dos Colchões. Procuro: '+d.get('size')+'; conforto: '+d.get('feel')+'; marca: '+d.get('brand')+'. Quero conhecer modelos, medidas, valores e disponibilidade.'),'_blank','noopener,noreferrer')});
})();
