'use strict';
(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const sections=[...document.querySelectorAll('[data-motion]')];
function staticMode(){sections.forEach(s=>s.dataset.motionState='static');document.querySelector('.ribbon-track').style.animationPlayState='paused';document.querySelectorAll('.hotspot').forEach(b=>b.classList.add('motion-paused'))}
if(reduced.matches){staticMode();return}if(!window.gsap||!window.ScrollTrigger){sections.forEach(s=>s.dataset.motionState='css-fallback');return}
gsap.registerPlugin(ScrollTrigger);const mobile=matchMedia('(max-width:600px)').matches;const travel=mobile?16:35;sections.forEach(s=>s.dataset.motionState='authored');
const header=document.querySelector('.header');let lenis;
if(!mobile&&matchMedia('(pointer:fine)').matches&&window.Lenis){lenis=new Lenis({lerp:.085,smoothWheel:true,anchors:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
ScrollTrigger.create({start:0,end:'max',onUpdate:s=>{gsap.set('.page-progress',{scaleX:s.progress});header.classList.toggle('is-scrolled',s.scroll()>45)}});
// Opening: one coordinated composition, room remains visible throughout.
gsap.from('.hero-room>img',{scale:1.07,duration:1.6,ease:'expo.out',clearProps:'transform'});gsap.from('.hero-copy h1',{x:-travel,duration:1.2,ease:'expo.out',clearProps:'transform'});gsap.from('.hero-actions,.hero-people',{y:travel/2,duration:1.2,stagger:.13,ease:'expo.out',clearProps:'transform'});
gsap.to('.hero-room>img',{y:mobile?15:55,scale:1.035,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:.8}});gsap.to('.light-sweep',{xPercent:30,ease:'none',scrollTrigger:{trigger:'.hero',start:'top bottom',end:'bottom top',scrub:1}});
// Discovery: horizontal spacing resolves, instead of repeating a fade.
gsap.from('.discovery-links a',{x:travel,stagger:.08,duration:.8,ease:'expo.out',scrollTrigger:{trigger:'.discovery',start:'top 88%'},clearProps:'transform'});
const room=document.querySelector('.explorer-room');gsap.from(room,{clipPath:'inset(0 6% 0 6%)',duration:1.2,ease:'expo.out',scrollTrigger:{trigger:room,start:'top 85%'},clearProps:'clipPath'});gsap.to('#featured-image',{scale:1.04,ease:'none',scrollTrigger:{trigger:room,start:'top bottom',end:'bottom top',scrub:1}});
document.addEventListener('paraiso:model',()=>{gsap.fromTo('#featured-image',{filter:'brightness(.82)',clipPath:'inset(0 0 0 4%)'},{filter:'brightness(1)',clipPath:'inset(0 0 0 0%)',duration:.65,ease:'expo.out',clearProps:'filter,clipPath'});gsap.fromTo('.explorer-info h3',{x:12},{x:0,duration:.5,ease:'expo.out',clearProps:'transform'})});
document.addEventListener('paraiso:feature',()=>{gsap.fromTo('.feature-line',{scaleX:.25},{scaleX:1,transformOrigin:'left',duration:.65,ease:'expo.out'});gsap.fromTo('.feature-description h4,.feature-description p',{x:9},{x:0,duration:.45,stagger:.04,ease:'expo.out',clearProps:'transform'})});
gsap.from('.product',{y:travel,stagger:.055,duration:.8,ease:'expo.out',scrollTrigger:{trigger:'.product-grid',start:'top 88%'},clearProps:'transform'});
document.addEventListener('paraiso:filter',()=>{ScrollTrigger.refresh();gsap.fromTo('.product:not([hidden]) .product-image',{clipPath:'inset(0 0 5% 0)'},{clipPath:'inset(0 0 0 0)',duration:.6,stagger:.035,ease:'expo.out',clearProps:'clipPath'})});
document.querySelectorAll('.spring-diagram path').forEach(p=>{const length=p.getTotalLength();gsap.fromTo(p,{strokeDasharray:length,strokeDashoffset:length},{strokeDashoffset:0,ease:'none',scrollTrigger:{trigger:'.spring-study',start:'top 90%',end:'center 45%',scrub:.6}})});gsap.from('.tech-comparison>div',{y:travel/2,stagger:.15,duration:.75,ease:'expo.out',scrollTrigger:{trigger:'.tech-comparison',start:'top 92%'},clearProps:'transform'});
gsap.from('.guide-room',{clipPath:'inset(0 12% 0 0)',duration:1,ease:'expo.out',scrollTrigger:{trigger:'.guide-room',start:'top 85%'},clearProps:'clipPath'});document.addEventListener('paraiso:guide',()=>{gsap.fromTo('.guide-summary',{y:6},{y:0,duration:.4,ease:'expo.out',clearProps:'transform'})});
gsap.from('.about-photo',{clipPath:'inset(4% 7% 4% 7%)',duration:1.3,ease:'expo.out',scrollTrigger:{trigger:'.about',start:'top 82%'},clearProps:'clipPath'});gsap.from('.about-copy h2,.about-copy>p,.about-points span',{x:travel,stagger:.065,duration:.9,ease:'expo.out',scrollTrigger:{trigger:'.about',start:'top 78%'},clearProps:'transform'});
gsap.from('.questions details',{clipPath:'inset(0 8% 0 0)',stagger:.075,duration:.85,ease:'expo.out',scrollTrigger:{trigger:'.questions',start:'top 88%'},clearProps:'clipPath'});
gsap.fromTo('.visit-room img',{scale:1.1},{scale:1,ease:'none',scrollTrigger:{trigger:'.visit',start:'top bottom',end:'center center',scrub:.9}});gsap.from('.visit-panel',{x:travel,duration:1,ease:'expo.out',scrollTrigger:{trigger:'.visit',start:'top 78%'},clearProps:'transform'});gsap.fromTo('.footer-word',{letterSpacing:'.025em'},{letterSpacing:'-.02em',ease:'none',scrollTrigger:{trigger:'footer',start:'top bottom',end:'bottom bottom',scrub:.8}});
// Keep ambient loops stopped when they cannot be seen.
const observer=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{target.classList.toggle('motion-paused',!isIntersecting);target.querySelectorAll('.ribbon-track').forEach(t=>t.style.animationPlayState=isIntersecting&&!document.hidden?'running':'paused')}),{threshold:.05});document.querySelectorAll('.brand-ribbon,.explorer-room').forEach(e=>observer.observe(e));document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('tab-hidden',document.hidden);if(!document.hidden)ScrollTrigger.refresh()});
reduced.addEventListener('change',()=>location.reload());window.addEventListener('load',()=>ScrollTrigger.refresh());
})();
