'use strict';
(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)'),hero=document.querySelector('.hero'),canvas=document.getElementById('light-field');
const gsap=window.gsap,ScrollTrigger=window.ScrollTrigger;
if(gsap&&ScrollTrigger){
 gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();
 mm.add('(prefers-reduced-motion: no-preference)',()=>{
  document.documentElement.classList.add('motion-ready');
  let lenis=null;const ambient=[];let animateLenis=null;
  if(fine.matches&&window.Lenis){lenis=new Lenis({lerp:.09,smoothWheel:true,syncTouch:false,anchors:true});lenis.on('scroll',ScrollTrigger.update);animateLenis=time=>lenis.raf(time*1000);gsap.ticker.add(animateLenis,false,true);gsap.ticker.lagSmoothing(0)}
  const reveal=gsap.timeline({defaults:{ease:'expo.out',duration:1.45}});reveal.from('.hero h1 .line>span',{yPercent:35,opacity:.7,stagger:.13}).from('.hero-offer',{y:25,opacity:.6},.35).from('.hero-photo',{y:55,rotation:8,opacity:.7},.15);
  gsap.timeline({scrollTrigger:{trigger:hero,start:'top top',end:'bottom top',scrub:1}}).to('.hero-copy',{y:-95,scale:.96,ease:'none'},0).to('.hero-photo',{y:-155,rotation:-3,ease:'none'},0).to('.hero-atmosphere',{y:90,scale:1.1,ease:'none'},0).to('.orbit-two',{rotation:45,y:130,ease:'none'},0).to('.ribbon',{rotation:1.4,y:-25,ease:'none'},.1);
  const breathing=gsap.to('.portrait-window img',{scale:1.045,duration:9,ease:'sine.inOut',yoyo:true,repeat:-1,paused:true});ambient.push(breathing);ScrollTrigger.create({trigger:hero,start:'top bottom',end:'bottom top',onToggle:s=>s.isActive&&!document.hidden?breathing.play():breathing.pause()});
  const arc=gsap.to('.orbit-one',{rotation:'+=18',duration:16,ease:'sine.inOut',yoyo:true,repeat:-1,paused:true});ambient.push(arc);ScrollTrigger.create({trigger:hero,start:'top bottom',end:'bottom top',onToggle:s=>s.isActive&&!document.hidden?arc.play():arc.pause()});
  ScrollTrigger.create({trigger:'.castor-feature',start:'top top',end:'bottom bottom',onUpdate:s=>{document.querySelector('.castor-feature').style.setProperty('--scene',s.progress.toFixed(3));window.ParaisoScene.setFeatured(Math.min(2,Math.floor(s.progress*3)))},onLeave:()=>window.ParaisoScene.resetManual(),onLeaveBack:()=>window.ParaisoScene.resetManual()});
  gsap.timeline({scrollTrigger:{trigger:'.castor-feature',start:'top bottom',end:'bottom bottom',scrub:1}}).fromTo('.castor-backtype',{xPercent:10,scale:.91},{xPercent:-8,scale:1.08,ease:'none'},0).fromTo('.feature-images',{y:45,rotation:3},{y:-28,rotation:-3,ease:'none'},0).fromTo('.castor-top',{y:32},{y:0,ease:'none'},0);
  document.querySelectorAll('[data-lines]').forEach(el=>{gsap.from(el,{y:28,clipPath:'inset(0% 0% 12% 0%)',opacity:.72,duration:1.25,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 89%',once:true}})});
  gsap.from('[data-mask]',{clipPath:'inset(0% 0% 25% 0%)',y:55,rotation:1,duration:1.5,ease:'expo.out',scrollTrigger:{trigger:'.about',start:'top 80%',once:true}});
  document.querySelectorAll('.product').forEach((card,i)=>{gsap.from(card,{y:i%2?62:35,opacity:.75,duration:1.2,ease:'expo.out',scrollTrigger:{trigger:card,start:'top 94%',once:true}});gsap.from(card.querySelector('img'),{scale:1.1,duration:1.4,ease:'expo.out',scrollTrigger:{trigger:card,start:'top 88%',once:true}})});
  const statement=gsap.timeline({scrollTrigger:{trigger:'.rest-statement',start:'top 80%',end:'bottom 70%',scrub:.7}});statement.fromTo('.statement-text span',{opacity:.4,y:15},{opacity:1,y:0,stagger:.22,ease:'none'},0).to('.statement-orbit',{rotation:20,xPercent:-5,ease:'none'},0);
  gsap.from('.guide-form fieldset',{y:25,opacity:.7,stagger:.18,duration:1.2,ease:'expo.out',scrollTrigger:{trigger:'.comfort',start:'top 75%',once:true}});
  gsap.from('.questions details',{y:20,opacity:.75,stagger:.1,duration:1,ease:'expo.out',scrollTrigger:{trigger:'.questions',start:'top 85%',once:true}});
  gsap.fromTo('.visit-media',{scale:1.12,y:50,clipPath:'inset(10% 5% 0% 5% round 25px)'},{scale:1,y:0,clipPath:'inset(0% 0% 0% 0% round 0px)',ease:'none',scrollTrigger:{trigger:'.visit',start:'top bottom',end:'bottom bottom',scrub:1}});
  const mediaBreath=gsap.to('.visit-media img',{scale:1.035,duration:10,yoyo:true,repeat:-1,ease:'sine.inOut',paused:true});ambient.push(mediaBreath);ScrollTrigger.create({trigger:'.visit',start:'top bottom',end:'bottom top',onToggle:s=>s.isActive&&!document.hidden?mediaBreath.play():mediaBreath.pause()});
  gsap.to('.footer-word',{x:15,ease:'none',scrollTrigger:{trigger:'footer',start:'top bottom',end:'bottom bottom',scrub:1}});
  const magnets=[];if(fine.matches){document.querySelectorAll('.button').forEach(b=>{const x=gsap.quickTo(b,'x',{duration:.55,ease:'expo.out'}),y=gsap.quickTo(b,'y',{duration:.55,ease:'expo.out'});const move=e=>{const r=b.getBoundingClientRect();x((e.clientX-r.left-r.width/2)*.09);y((e.clientY-r.top-r.height/2)*.15)},leave=()=>{x(0);y(0)};b.addEventListener('pointermove',move);b.addEventListener('pointerleave',leave);magnets.push([b,move,leave])})}
  const refresh=()=>ScrollTrigger.refresh(),menu=e=>{if(lenis)e.detail.open?lenis.stop():lenis.start()},visibility=()=>{document.body.classList.toggle('is-page-hidden',document.hidden);ambient.forEach(a=>{const section=a.targets()[0].closest('.hero,.visit');const r=section.getBoundingClientRect();document.hidden||r.bottom<=0||r.top>=innerHeight?a.pause():a.play()});};
  document.addEventListener('paraiso:filter',refresh);document.addEventListener('paraiso:menu',menu);document.addEventListener('visibilitychange',visibility);document.fonts.ready.then(refresh);
  return()=>{document.documentElement.classList.remove('motion-ready');if(animateLenis)gsap.ticker.remove(animateLenis);if(lenis)lenis.destroy();ambient.forEach(a=>a.kill());magnets.forEach(([b,m,l])=>{b.removeEventListener('pointermove',m);b.removeEventListener('pointerleave',l)});document.removeEventListener('paraiso:filter',refresh);document.removeEventListener('paraiso:menu',menu);document.removeEventListener('visibilitychange',visibility)};
 });
 const progress=gsap.quickSetter('.page-progress','scaleX');ScrollTrigger.create({start:0,end:()=>document.documentElement.scrollHeight-innerHeight,onUpdate:s=>progress(s.progress)});
}
// Native scrolling and content remain available when a motion dependency fails.
if(!canvas||reduced.matches)return;
const gl=canvas.getContext('webgl',{alpha:true,antialias:false,powerPreference:'low-power'});if(!gl){canvas.hidden=true;return}
const vertex='attribute vec2 a;varying vec2 uv;void main(){uv=a*.5+.5;gl_Position=vec4(a,0.,1.);}';
const fragment=`precision mediump float;varying vec2 uv;uniform float t;uniform vec2 pointer;void main(){vec2 p=uv;float phase=p.x*8.+sin(p.y*4.+t*.17)*.7;float fold=sin(phase+t*.13)*.5+.5;float light=pow(fold,6.)*.3;float interaction=max(0.,1.-distance(p,pointer)*2.)*.08;vec3 petrol=vec3(.018,.22,.25);vec3 amber=vec3(.5,.25,.07);gl_FragColor=vec4(petrol+amber*light,.14+light*.4+interaction);}`;
function compile(type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){gl.deleteShader(shader);return null}return shader}
const v=compile(gl.VERTEX_SHADER,vertex),f=compile(gl.FRAGMENT_SHADER,fragment);if(!v||!f){canvas.hidden=true;return}const program=gl.createProgram();gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){canvas.hidden=true;return}gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const position=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);
const time=gl.getUniformLocation(program,'t'),pointer=gl.getUniformLocation(program,'pointer');let frame=0,last=0,visible=false,px=.35,py=.5;
function size(){const dpr=Math.min(devicePixelRatio||1,1.25);canvas.width=Math.round(canvas.clientWidth*dpr);canvas.height=Math.round(canvas.clientHeight*dpr);gl.viewport(0,0,canvas.width,canvas.height)}
function draw(now){if(!visible||document.hidden||reduced.matches){frame=0;return}if(now-last>40){last=now;gl.uniform1f(time,now/1000);gl.uniform2f(pointer,px,py);gl.drawArrays(gl.TRIANGLES,0,6)}frame=requestAnimationFrame(draw)}
function start(){if(visible&&!document.hidden&&!reduced.matches&&!frame)frame=requestAnimationFrame(draw)}
new IntersectionObserver(e=>{visible=e[0].isIntersecting;start()},{threshold:0}).observe(hero);hero.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=hero.getBoundingClientRect();px=(e.clientX-r.left)/r.width;py=1-(e.clientY-r.top)/r.height},{passive:true});addEventListener('resize',size,{passive:true});document.addEventListener('visibilitychange',start);reduced.addEventListener('change',start);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();visible=false;cancelAnimationFrame(frame);canvas.hidden=true});size();
})();
